* DONE <2020-05-13 Wed> almost there but..
  I'm stuck with this
  #+BEGIN_VERSE
  1>IPlug2_IPlug_APP_IPlugAPP_dialog.cpp.obj : error LNK2001: unresolved external symbol "struct HINSTANCE__ * gHINSTANCE" (?gHINSTANCE@@3PEAUHINSTANCE__@@EA)
1>IPlug2_IPlug_APP_IPlugAPP_main.cpp.obj : error LNK2001: unresolved external symbol "struct HINSTANCE__ * gHINSTANCE" (?gHINSTANCE@@3PEAUHINSTANCE__@@EA)
1>IPlug2_IPlug_APP_IPlugAPP_host.cpp.obj : error LNK2019: unresolved external symbol "class iplug::IPlugAPP * __cdecl iplug::MakePlug(struct iplug::InstanceInfo const &)" (?MakePlug@iplug@@YAPEAVIPlugAPP@1@AEBUInstanceInfo@1@@Z) referenced in function "public: __cdecl iplug::IPlugAPPHost::IPlugAPPHost(void)" (??0IPlugAPPHost@iplug@@QEAA@XZ)

  #+END_VERSE

  .. i wasn't including the source file (effect.cpp or aodplug.cpp whatever)

* TODO main.rc menu window..?
  maybe don't need this for the no gui but still.. hm..
* meson articles etc
  - https://medium.com/@germandiagogomez/getting-started-with-meson-in-c-part-2-58150354ff17
    - https://github.com/germandiagogomez/getting-started-with-meson
* <2020-06-04 Thu> IPlug2 as meson subproject
** options
   #+BEGIN_SRC meson
option('IGRAPHICS',
       type: 'array',
       choices: [
	 'NO_IGRAPHICS',
	 # possible graphics libraries
	 # see IGraphics.h
	 'IGRAPHICS_AGG',
	 'IGRAPHICS_CAIRO',
	 'IGRAPHICS_NANOVG',
	 'IGRAPHICS_LICE',
	 'IGRAPHICS_CANVAS',
	 'IGRAPHICS_SKIA',
	 # --

	 # other flags..?
	 # see files:
	 # IGraphics_include_in_plug_hdr.h
	 # IGraphics_select.h
	 # IGraphics.cpp
	 'IGRAPHICS_GLES2',
	 'IGRAPHICS_GLES3',
	 'IGRAPHICS_GL2',
	 'IGRAPHICS_GL3',
	 
	 'IGRAPHICS_IMGUI',

	 'IGRAPHICS_DRAWFILL_DIRECT',
	 'IGRAPHICS_CPU',
	 'IGRAPHICS_WEB_POINTERLOCK',
	 'IGRAPHICS_FREETYPE',

	 'IGRAPHICS_METAL',
	 'IGRAPHICS_IMGUI',
       ],
       value: ['NO_IGRAPHICS']
      )
  
   #+END_SRC
** conditional including IGraphics folder
   if ='IGRAPHICS= options doesn't have the
   =NO_IGRAPHICS=

   also how to easily go through the options
   and add the =define= statementes?

   #+BEGIN_SRC meson
add_project_arguments('-DNO_IGRAPHICS', language : 'cpp')   
   #+END_SRC

** IPlugControls meson example
   - Cannot open include file: 'nanosvg.h':
     adding =iplug2/Dependencies/IGraphics= dir
   - Cannot open include file: 'IControls.h'
     didn't have the subdirs =controls= etc..
   - Cannot open include file: 'nanovg.h'
     ~includes += include_directories('./NanoVG/src')~
   - Cannot open include file: 'stb_textedit.h'
   - igraphics..
     #+BEGIN_VERSE
     IGraphicsNanoVG.h(28,1): fatal error C1189: #error:  you must define either IGRAPHICS_GL2, IGRAPHICS_GLES2 etc or IGRAPHICS_METAL when using IGRAPHICS_NANOVG
     #+END_VERSE
     But see [[file:iPlug2/IGraphics/IGraphics_include_in_plug_hdr.h::IGRAPHICS_GL2]]
     imported from
     - IPlug_include_in_plug_hdr.h
     - IPlugControls.h
     - 

	  #+BEGIN_SRC c
     #elif defined IGRAPHICS_GL2 || defined IGRAPHICS_GL3
       #define IGRAPHICS_GL     
	  #+END_SRC

	  and i'm defining =IGRAPHICS_GL2=
	  temporarily added manually
	  #+BEGIN_SRC meson
     add_project_arguments('-DIGRAPHICS_GL', language : 'cpp')     
	  #+END_SRC
   - source files..
     #+BEGIN_VERSE
     cannot open source file "glad/glad.h"
     #+END_VERSE



   still have the problem with IGRAPHICS_GL..
   
** Comparison with existing example
   #+BEGIN_VERSE
   1>------ Build started: Project: IPlugControls-app, Configuration: Debug Win32 ------
1>asio.cpp
1>asiodrivers.cpp
1>asiolist.cpp
1>iasiothiscallresolver.cpp
1>RtAudio.cpp
1>RtMidi.cpp
1>IControls.cpp
1>IPopupMenuControl.cpp
1>ITextEntryControl.cpp
1>IControl.cpp
1>IGraphics.cpp
1>IGraphicsEditorDelegate.cpp
1>IGraphicsWin.cpp
1>IPlugAPP.cpp
1>IPlugAPP_dialog.cpp
1>IPlugAPP_host.cpp
1>IPlugAPP_main.cpp
1>IPlugAPIBase.cpp
1>IPlugParameter.cpp
1>IPlugPaths.cpp
1>IPlugPluginBase.cpp
1>IPlugProcessor.cpp
1>IPlugTimer.cpp
1>IPlugControls.cpp
1>IPlugControls-app.vcxproj -> W:\dev\_vst\iPlug2\Examples\IPlugControls\build-win\app\Win32\Debug\IPlugControls.exe

   #+END_VERSE

   #+BEGIN_VERSE
   1>------ Build started: Project: IPlugControls, Configuration: debug x64 ------
1>IPlugControls.cpp
1>IControl.cpp
1>IGraphics.cpp
1>IGraphicsEditorDelegate.cpp
1>IControls.cpp
1>IPopupMenuControl.cpp
1>ITextEntryControl.cpp
1>IGraphicsNanoVG.cpp
1>W:\dev\_tmp\mesonIPlug\examples\IPlugControls\subprojects\iplug2\IGraphics\Drawing\IGraphicsNanoVG.h(28,31): fatal error C1189: #error:  you must define either IGRAPHICS_GL2, IGRAPHICS_GLES2 etc or IGRAPHICS_METAL when using IGRAPHICS_NANOVG

   #+END_VERSE

   ..and now it's building!
   #+BEGIN_VERSE
   Code	File	Line	Column
2>IControl.cpp		60	11
2>IPlugControls.cpp		5	16
2>IGraphics.cpp		84	12
2>IGraphicsEditorDelegate.cpp		118	26
2>IControls.cpp		142	12
2>IPopupMenuControl.cpp		173	20
2>ITextEntryControl.cpp		198	20
2>IGraphicsWin.cpp		222	15
2>IPlugAPIBase.cpp		252	15
2>IPlugParameter.cpp		271	17
2>IPlugPaths.cpp		276	13
2>IPlugPluginBase.cpp		278	18
2>IPlugProcessor.cpp		293	17
2>IPlugTimer.cpp		301	13
2>IPlugAPP.cpp		302	11
2>IPlugAPP_dialog.cpp		324	18
2>IPlugAPP_host.cpp		359	16
2>IPlugAPP_main.cpp		381	16
2>RtAudio.cpp		405	10
2>asio.cpp		406	7
2>asiodrivers.cpp		407	14
2>asiolist.cpp		408	11
2>iasiothiscallresolver.cpp		409	24
2>RtMidi.cpp		410	9

   #+END_VERSE


   
*** Linker
    working example
    #+BEGIN_EXAMPLE
    /OUT:"W:\dev\_vst\iPlug2\Examples\IPlugControls\build-win\app\Win32\Debug\IPlugControls.exe" /MANIFEST /NXCOMPAT /PDB:"W:\dev\_vst\iPlug2\Examples\IPlugControls\build-win\pdbs\IPlugControls-app_Win32.pdb" /DYNAMICBASE "dsound.lib" "winmm.lib" "wininet.lib" "comctl32.lib" "Shlwapi.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "comdlg32.lib" "advapi32.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "odbc32.lib" "odbccp32.lib"

 /IMPLIB:"W:\dev\_vst\iPlug2\Examples\IPlugControls\build-win\app\Win32\Debug\int\IPlugControls.lib" /DEBUG:FASTLINK /MACHINE:X86 /PGD:"W:\dev\_vst\iPlug2\Examples\IPlugControls\build-win\app\Win32\Debug\IPlugControls.pgd" /SUBSYSTEM:WINDOWS /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /ManifestFile:"W:\dev\_vst\iPlug2\Examples\IPlugControls\build-win\app\Win32\Debug\int\IPlugControls.exe.intermediate.manifest" /ERRORREPORT:PROMPT /NOLOGO /LIBPATH:"W:\dev\_vst\iPlug2\Examples\IPlugControls\projects\..\..\..\Dependencies\Build\win\Win32\Debug" /LIBPATH:"W:\dev\_vst\iPlug2\Examples\IPlugControls\projects\..\..\..\Dependencies\IPlug\AAX_SDK\Libs\Debug" /LIBPATH:"C:\Program Files\Faust\lib" /TLBID:1 
    #+END_EXAMPLE
    
    meson
    #+BEGIN_EXAMPLE
    /OUT:".\IPlugControls.exe" /MANIFEST "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib" /RELEASE /IMPLIB:"IPlugControls.exe.lib" /DEBUG:FULL /MACHINE:X64 /INCREMENTAL /SUBSYSTEM:WINDOWS /NOLOGO 

/DYNAMICBASE "dsound.lib" "winmm.lib" "wininet.lib" "comctl32.lib" "Shlwapi.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "comdlg32.lib" "advapi32.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "odbc32.lib" "odbccp32.lib" /TLBID:1 
    #+END_EXAMPLE
* <2020-06-08 Mon> linux
** notes..
  - https://github.com/iPlug2/iPlug2/blob/linux/IGraphics/IGraphics_include_in_plug_hdr.h
  - 

  #+BEGIN_SRC sh

rm -r examples/IPlugControls/subprojects/iPlug2
ln -s `pwd`/../iPlug2 `pwd`/examples/IPlugControls/subprojects/
  #+END_SRC

  ../subprojects/iPlug2/IPlug/IPlugTimer.h:31:10: fatal error: swell.h: No such file or directory

  got an error from =VST3_SDK/base/source/fdebug.h=
  #+BEGIN_SRC c
#if !defined (DEVELOPMENT) && !defined (RELEASE) 
	#ifdef _DEBUG
		#define DEVELOPMENT 1
	#elif defined (NDEBUG)
		#define RELEASE 1
	#else
		#error DEVELOPMENT, RELEASE, _DEBUG, or NDEBUG  must be defined!
	#endif
#endif
  #+END_SRC
  

  #+BEGIN_VERSE
  subprojects/iPlug2/Dependencies/IGraphics/./xcbt/xcbt.c:30:10: fatal error: X11/Xlib-xcb.h: No such file or directory
   30 | #include <X11/Xlib-xcb.h>
      |          ^~~~~~~~~~~~~~~~

  #+END_VERSE

  searching for installed libs
  #+BEGIN_SRC sh
ldconfig -p | grep x11
apt-cache search xcb | grep dev

sudo apt-get install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev
  #+END_SRC

  #+BEGIN_EXAMPLE
  undefined reference to `dlopen'
  #+END_EXAMPLE
  -ldl

  #+BEGIN_EXAMPLE
  undefined reference to `gladLoadGLX'
  #+END_EXAMPLE
  #+BEGIN_SRC sh
sudo apt-get install libglew-dev
  #+END_SRC

  link to libgl
  #+BEGIN_SRC sh
sudo apt install libgl1-mesa-glx   
  #+END_SRC
** notes v2
   see
   - common-linux.mk and
   - Makefile

   #+BEGIN_EXAMPLE
_GLAD_PATH := $(_IGRAPHICS_DEPS_PATH)/glad_GL2
	IPSRC_DIR += $(_GLAD_PATH)/src
	IPINC_DIR += $(_GLAD_PATH)/include
	_GLAD_GLX_PATH := $(_IGRAPHICS_DEPS_PATH)/glad_GLX
	IPSRC_DIR += $(_GLAD_GLX_PATH)/src
	IPINC_DIR += $(_GLAD_GLX_PATH)/include
  IPSRC_DIR += $(_IGRAPHICS_DEPS_PATH)/xcbt

   #+END_EXAMPLE
** DONE trying the make file
   [[file:~/dev/actondev/iPlug2/Examples/Makefile]]
   #+BEGIN_SRC sh
sudo apt-get install libtool autoconf
   #+END_SRC
   #+BEGIN_SRC sh :session *linux-make*
cd ../iPlug2
cd Examples/IPlugControls
make -f ../Makefile

make -f ../Makefile CLEAN

rm -r ../Build
   #+END_SRC

   #+BEGIN_EXAMPLE
   Package gdk-3.0 was not found in the pkg-config search path
   #+END_EXAMPLE

   #+BEGIN_SRC sh
apt-cache search gdk

# wtf? typo
sudo apt install libgdk3.0-cil-dev

apt-cache search libgtk

sudo apt install libgtk-3-dev
   #+END_SRC


   #+BEGIN_EXAMPLE
   Generating resource ...
php /home/actondev/dev/actondev/iPlug2/WDL/swell/mac_resgen.php ../Build/Linux-x86_64/IPlugControls/APP/.obj/resources/main.rc
make: php: Command not found
   #+END_EXAMPLE

   #+BEGIN_SRC sh
sudo apt install php
   #+END_SRC
   
** DONE can build IPlugControls.. but no window (couldn't attach gui)

   #+BEGIN_EXAMPLE
   trying to start audio stream @ 44100 sr, 512 buffer size
indev = 0:PulseAudio
outdev = 0:PulseAudio
inputs = 0
outputs = 2
SWELL: swt 'IPlugControls'
APP: Initial socket size: 1024x768
IGraphics NanoVG @ 60 FPS
couldn't attach gui
SWELL: swt 'IPlugControls'
SWELL: swt 'IPlugControls'

   #+END_EXAMPLE
   instead, in the built example with make

   #+BEGIN_EXAMPLE
trying to start audio stream @ 44100 sr, 512 buffer size
indev = 0:hw:HDA Intel PCH,0
outdev = 0:hw:HDA Intel PCH,0
inputs = 0
outputs = 2

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.

APP: Initial socket size: 1024x768
IGraphics NanoVG @ 60 FPS
INFO: resized to 1024x768
WARNING: parent is not resized, but I (should) have no control on it on X... XEMBED?

   #+END_EXAMPLE
* DONE Meson --backend vs : Visual Studio command prompt

  https://stackoverflow.com/questions/45821276/source-vsdevcmd-bat-from-cygwin

  #+BEGIN_SRC sh :session *vs-cmd*
cmd //k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
meson setup buildvs --backend vs
meson buildvs --backend vs --reconfigure
meson compile -C buildvs

# to cleanup/regenerate
rm -rf buildvs
  #+END_SRC

  Now I can run in this session any msys2 program (meson, ninja etc) but I also have the environment of visual studio

* Meson notes
  - Should I use subdir or subproject?
    The answer is almost always subdir
  - https://mesonbuild.com/Users.html
  - https://mesonbuild.com/Reference-manual.html#declare_dependency
  - https://stackoverflow.com/questions/34602912/with-meson-build-can-i-define-intra-project-dependencies

** depencdencies?
   https://mesonbuild.com/Wrap-best-practices-and-tips.html#page-description
   #+BEGIN_VERSE
   myheader = custom_target(...)
mylibrary = shared_library(...)
mydep = declare_dependency(link_with : mylibrary,
  include_directories : include_directories(...),
  sources : myheader)

And then you can use the dependency in the usual way:

executable('dep_using_exe', 'main.c',
  dependencies : mydep)

   #+END_VERSE
* Example APP for iplug
** 
** Command line
   /JMC /MP /GS /W3 /wd"4996" /wd"4250" /wd"4018" /wd"4267" /wd"4068" /Zc:wchar_t
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\IPlug\APP"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\IPlug\RTAudio\include"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\IPlug\RTAudio"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\IPlug\RTMidi"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\WDL"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\IPlug"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\IPlug\Extras"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\IPlug\Extras\Synth"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\IPlug\Extras\Faust"
   /I"W:\dev\_vst\AOD_IPlug01\\resources"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\IGraphics"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\IGraphics\Controls"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\IGraphics\Drawing"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\IGraphics\Platforms"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\IGraphics\Extras"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\WDL\lice"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\IGraphics\NanoSVG\src"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\IGraphics\NanoVG\src"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\IGraphics\AGG\agg-2.4\include"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\IGraphics\AGG\agg-2.4\font_freetype"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\IGraphics\AGG\agg-2.4\include\util"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\IGraphics\AGG\agg-2.4\include\platform\win32"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\IGraphics\AGG\agg-2.4\src"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\IGraphics\AGG\agg-2.4\src\platform\win32"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\IGraphics\Cairo"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\Build\src"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\WDL\libpng"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\WDL\zlib"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\Build\src\freetype\include"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\IGraphics\STB"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\IGraphics\imgui"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\IGraphics\imgui\examples"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\Build\src\skia"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\Build\src\skia\include\core"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\Build\src\skia\include\effects"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\Build\src\skia\include\config"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\Build\src\skia\include\utils"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\Build\src\skia\include\gpu"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\Build\src\skia\experimental\svg\model"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\IGraphics\yoga"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\IGraphics\yoga\yoga"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\IGraphics\glad_GL2\include"
   /I"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\IGraphics\glad_GL2\src"
   /I"W:\dev\_vst\AOD_IPlug01\"

   /ZI /Gm- /Od /Fd"W:\dev\_vst\AOD_IPlug01\build-win\app\x64\Debug\int\vc142.pdb" /Zc:inline /fp:precise /D "APP_API" /D "__WINDOWS_DS__" /D "__WINDOWS_MM__" /D "__WINDOWS_ASIO__" /D "IPLUG_EDITOR=1" /D "IPLUG_DSP=1" /D "_DEBUG" /D "IGRAPHICS_NANOVG" /D "IGRAPHICS_GL2" /D "WIN32" /D "_CRT_SECURE_NO_DEPRECATE" /D "_CRT_NONSTDC_NO_DEPRECATE" /D "NOMINMAX" /D "_MBCS" /errorReport:prompt /WX- /Zc:forScope /RTC1 /Gd /MTd /std:c++14 /FC /Fa"W:\dev\_vst\AOD_IPlug01\build-win\app\x64\Debug\int\" /EHsc /nologo /Fo"W:\dev\_vst\AOD_IPlug01\build-win\app\x64\Debug\int\" /Fp"W:\dev\_vst\AOD_IPlug01\build-win\app\x64\Debug\int\AOD_IPlug01.pch" /diagnostics:column 
** Linking cmd
   W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\Build\win\x64\Debug


   /OUT:"W:\dev\_vst\AOD_IPlug01\build-win\app\x64\Debug\AOD_IPlug01.exe" /MANIFEST /NXCOMPAT /PDB:"W:\dev\_vst\AOD_IPlug01\build-win\pdbs\AOD_IPlug01-app_x64.pdb"
/DYNAMICBASE "dsound.lib" "winmm.lib" "wininet.lib" "comctl32.lib" "Shlwapi.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "comdlg32.lib" "advapi32.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "odbc32.lib" "odbccp32.lib" "csv952.lib" 

/IMPLIB:"W:\dev\_vst\AOD_IPlug01\build-win\app\x64\Debug\int\AOD_IPlug01.lib" /DEBUG:FASTLINK /MACHINE:X64 /PGD:"W:\dev\_vst\AOD_IPlug01\build-win\app\x64\Debug\AOD_IPlug01.pgd" /SUBSYSTEM:WINDOWS /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /ManifestFile:"W:\dev\_vst\AOD_IPlug01\build-win\app\x64\Debug\int\AOD_IPlug01.exe.intermediate.manifest" /ERRORREPORT:PROMPT /NOLOGO 

/LIBPATH:"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\Build\win\x64\Debug" 

/LIBPATH:"W:\dev\_vst\AOD_IPlug01\projects\..\..\iPlug2\Dependencies\IPlug\AAX_SDK\Libs\Debug" /LIBPATH:"C:\Program Files\Faust\lib"

/TLBID:1 
* projects
  - https://github.com/linuxmint/cinnamon-desktop/blob/master/libcinnamon-desktop/meson.build#L62
    install_headers ?
  - https://code.videolan.org/videolan/dav1d/-/blob/master/src/meson.build#L253
    libdav1d_entrypoints_objs = static_library(...).extract_all_objects()
    - dependencies: [stdatomic_dependency],

* emacs snippet
#+BEGIN_SRC emacs-lisp :results silent
(defun aod.meson/sources (dir regexp)
  (interactive "DDirectory:\nsRegexp: ")
  (message dir)
  (let* ((filenames (directory-files dir
				     t ; full path
				     regexp ;match
				     nil	;nosort
				     ))
	 (formatted (mapconcat (function (lambda (x)
					   (let ((relative-path (file-relative-name x ".")))
					     (format "'%s',\n" relative-path))))
			       filenames
			       " ")))
    (insert formatted)))
#+END_SRC

  - dired-mark-files-containing-regexp 
    cpp
  - =w= dired-copy-filename-as-killd
* TODO CI
  - https://circleci.com/docs/2.0/hello-world-windows/
* Troubleshooting
** <2020-06-03 Wed> not launching??
   on =IPlugAPP_main.cpp=
   - not defined =APP_ALLOW_MULTIPLE_INSTANCES=
   - =HANDLE hMutex = OpenMutex(MUTEX_ALL_ACCESS, 0, BUNDLE_NAME); // BUNDLE_NAME used because it won't have spaces in it= returns something..
   - so it tries to bring it to front..


   #+BEGIN_SRC sh
ps -W | grep -i iplug
   #+END_SRC

   #+RESULTS:
   : 74008       0       0       8472  ?              0 20:53:46 W:\dev\_tmp\mesonIPlug\examples\nogui01\buildvs\iplug_exe.exe


   Note: these are the collumns
   #+BEGIN_EXAMPLE
         PID    PPID    PGID     WINPID   TTY         UID    STIME COMMAND
   #+END_EXAMPLE

   #+BEGIN_SRC sh
taskkill //f //pid 8472
   #+END_SRC
* <2020-09-04 Fri> reaper Extension
  - [X] windows
  - [X] linux
    almost there.. the =extensions= menus appears in reaper, but no entry is there
    ok fixed! was in =ReaperExt_include_in_plug_src.h= and see the =OS X has one extra menu=
    in windows the =GetSubMenu= was passing =8= as 2nd argument, =else= 9.. linux also has to pass =8=
